<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<UmbracoMajor Condition="'$(UmbracoMajor)' == ''">17</UmbracoMajor>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFrameworks>net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Authors>Enterspeed</Authors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(UmbracoMajor)' == '18'">
		<TargetFrameworks>net10.0</TargetFrameworks>
		<DefineConstants>$(DefineConstants);UMBRACO_18_OR_GREATER</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Enterspeed.Source.UmbracoCms.V14Plus.Tests" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'net10.0'">
		<PackageReference Include="Enterspeed.Source.Sdk" Version="2.0.4" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Enterspeed.Source.Sdk" Version="2.0.7" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
		<PackageReference Include="Umbraco.Cms.Core" Version="9.4.0" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="9.4.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Umbraco.Cms.Core" Version="10.4.0" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="10.4.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
		<PackageReference Include="Umbraco.Cms.Core" Version="11.0.0" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="11.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Umbraco.Cms.Core" Version="13.0.0" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="13.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Umbraco.Cms.Core" Version="15.0.0" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="15.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0' and '$(UmbracoMajor)' != '18'">
		<PackageReference Include="Umbraco.Cms.Core" Version="17.0.0" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="17.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0' and '$(UmbracoMajor)' == '18'">
		<PackageReference Include="Umbraco.Cms.Core" Version="[18.0.2, 19.0.0)" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="[18.0.2, 19.0.0)" />
	</ItemGroup>
	<Target Name="RemoveLuceneAnalyzer" BeforeTargets="CoreCompile">
		<ItemGroup>
			<Analyzer Remove="@(Analyzer)" Condition="%(FileName) == 'Lucene.Net.CodeAnalysis.CSharp'" />
		</ItemGroup>
	</Target>

</Project>
